version: '3.4'
services:
  h2:
    image: hvadriano/rest-with-spring-boot-h2
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_spring_boot_h2
    ports:
      - "3309:3306"
    networks:
      - rest-with-spring-boot-network-h2
  rest-with-spring-boot-h2-app:
    image: hvadriano/rest-with-spring-boot-h2-app
    restart: always
    build: ./RestWithSpringBoot
    working_dir: /RestWithSpringBoot
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./RestWithSpringBoot:/RestWithSpringBoot
      - ~/.m2:/root/.m2
    ports:
      - "8083:8080"
    command: mvn clean spring-boot:run
    links:
      - h2
    depends_on:
      - h2
    networks:
      - rest-with-spring-boot-network-h2
networks:
    rest-with-spring-boot-network-h2:
        driver: bridge